### ISSUE TITLE
cjs failure

### ISSUE THREAD

**Issue by danielroe** [unjsio/mkdist#3]
when passing in `{ format: 'cjs' }` I get the following error:
```
 ERROR  The "path" argument must be of type string. Received undefined                                    12:19:22

  at validateString (internal/validators.js:124:11)
  at dirname (path.js:1128:5)
  at t.transform.Object.assign.legacy (node_modules/jiti/dist/jiti.js:1:40213)
  at Function.f [as transform] (node_modules/jiti/dist/jiti.js:1:40499)
  at jsLoader (node_modules/mkdist/dist/index.js:35:44)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async loadFile (node_modules/mkdist/dist/index.js:83:23)
  at async vueLoader (node_modules/mkdist/dist/index.js:57:24)
  at async loadFile (node_modules/mkdist/dist/index.js:83:23)
  at async Object.mkdist (node_modules/mkdist/dist/index.js:115:21)
```

**Comment by pi0** [comment]
Needs reproduction :)

**Comment by danielroe** [comment]
https://codesandbox.io/s/confident-darwin-csuwq?file=/src/index.js:84-100
